const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const file = path.join(__dirname, '..', 'autogestion', '.htaccess');
const source = fs.readFileSync(file, 'utf8');
const router = fs.readFileSync(path.join(__dirname, '..', 'autogestion', 'server', 'router.php'), 'utf8');
const api = fs.readFileSync(path.join(__dirname, '..', 'autogestion', 'js', 'api.js'), 'utf8');
const payments = fs.readFileSync(path.join(__dirname, '..', 'autogestion', 'server', 'Payments.php'), 'utf8');
const entrypoint = fs.readFileSync(path.join(__dirname, '..', 'autogestion', 'api.php'), 'utf8');
const deployment = fs.readFileSync(path.join(__dirname, '..', '.cpanel.yml'), 'utf8');

assert.match(source, /^Options -Indexes$/m);
assert.match(source, /^DirectoryIndex index\.html$/m);
assert.doesNotMatch(source, /^DirectoryIndex disabled$/m);
assert.doesNotMatch(source, /RewriteRule/);
assert.match(source, /FilesMatch "\^\(\?!api\\\.php\$\)\.\+\\\.php\$"/);
assert.match(router, /Content-Security-Policy:[^\n]*https:\/\/web\.central\.chat/);
assert.match(router, /\$measurementOrigin/);
assert.match(router, /===\s*'api\.php'/);
assert.match(api, /return `api\.php\?/);
assert.doesNotMatch(api, /production-router\.php/);
assert.doesNotMatch(api, /fetch\(`api\//);
assert.match(payments, /route=payment-return/);
assert.match(payments, /\/api\.php\?/);
assert.match(entrypoint, /dirname\(__DIR__,2\)/);
assert.match(entrypoint, /require __DIR__\.'\/server\/router\.php'/);
assert.match(deployment, /autogestion\/api\.php/);
assert.match(deployment, /autogestion\/server\/PhantomSoap\.php/);
assert.doesNotMatch(deployment, /server\/production-router\.php/);
console.log('Mi USITTEL root PHP entrypoint: 18 assertions');
