import { runtime, money } from './data.js';
import { escapeHTML as e, button } from './components.js';

export function paymentPanel() {
  if (!runtime.paymentsEnabled) return '';
  const labels = { CREATING: 'Preparando pago...', PENDING: 'Pago pendiente', CONFIRMED: 'Pago confirmado', CANCELLED: 'Pago cancelado', REJECTED: 'Pago rechazado', UNCONFIRMED: 'No pudimos confirmar el pago' };
  const canCheck = state => !['CONFIRMED', 'CANCELLED', 'REJECTED'].includes(state);
  const postingCopy = a => a.phantom_payment_posted ? 'El pago ya fue registrado en Phantom.' : a.phantom_posting_state === 'POST_UNCONFIRMED' || a.phantom_posting_state === 'POSTING' ? 'SIRO confirmó el pago. Estamos verificando la actualización en Phantom; no hace falta volver a pagar.' : a.phantom_posting_state === 'NEEDS_REVIEW' ? 'SIRO confirmó el pago y la factura cambió en Phantom. La actualización requiere verificación.' : 'SIRO confirmó el pago. Estamos actualizando tu cuenta; el saldo puede tardar en reflejarse.';
  return `<section class="payment-status" aria-label="Movimientos de pago" aria-live="polite"><h2>Últimos movimientos</h2>${runtime.paymentError ? `<p role="alert">${e(runtime.paymentError)}</p>` : ''}${runtime.paymentItems.length ? runtime.paymentItems.map(a => `<div class="commercial-option"><h3>${a.phantom_payment_posted ? 'Pago registrado' : (labels[a.state] || labels.UNCONFIRMED)}</h3><p>Factura ${e(a.idt)} · ${money(a.amount)}</p><p class="field-hint">${a.siro_payment_confirmed ? postingCopy(a) : 'El saldo y el estado de la factura siguen siendo los informados por Phantom.'}</p>${canCheck(a.state) ? button('Consultar estado', 'payment-check', { secondary: true, attrs: `data-attempt="${e(a.attempt_id)}"` }) : ''}${runtime.phantomPostingEnabled && a.can_post_to_phantom ? button('Actualizar cuenta', 'payment-post', { secondary: true, attrs: `data-attempt="${e(a.attempt_id)}"` }) : ''}${a.can_resume ? button('Continuar en SIRO', 'pay', { secondary: true, iconName: 'external-link', attrs: `data-id="${e(a.idt)}"` }) : ''}</div>`).join('') : '<p class="muted">Todavía no hay movimientos para mostrar.</p>'}<p class="field-hint payment-provider-summary">El pago se realiza en el portal oficial de SIRO. Mi USITTEL confirma el resultado y mantiene separada la actualización posterior en Phantom.</p></section>`;
}
