import { servicePage, contractedProducts } from './service-view.js';
import { paymentPanel } from './payment-view.js';
import { customer, invoices, ticket, money, debt, credit, runtime, planLabel, addressLabel, connectivityLabel } from './data.js';
import { logo, status, button, input, invoiceTable, sectionLink, icon, escapeHTML as e } from './components.js';
function attentionButton() {
  return '<button type="button" class="button" data-action="chat">Hablar con nosotros</button>';
}

export function login() {
  return `<header class="login-header">${logo()}</header><main id="main" class="login-main"><h1 tabindex="-1">Mi USITTEL</h1><form id="login-form">${input('Usuario', 'username', { value: runtime.mode === 'demo' ? 'agustin.demo' : '', autocomplete: 'off' })}${input('Contraseña', 'password', { type: 'password', value: runtime.mode === 'demo' ? 'usittel-demo' : '', autocomplete: 'off' })}${button('Ingresar', '', { type: 'submit' })}${runtime.mode === 'demo' ? '<p class="login-note">Acceso de demostración. Usá los datos precargados.</p>' : '<p class="login-note">Ingresá con tus credenciales actuales de autogestión.</p>'}</form><section class="attention-login-help" aria-label="Ayuda para ingresar"><p>¿No podés ingresar?</p><div><button class="recovery-link" data-action="recover">Recuperar acceso</button></div></section></main>`;
}
export function home() {
  return `<h1 tabindex="-1">${customer.name ? 'Hola, ' + e(customer.name) : 'Inicio'}</h1><div class="dashboard-summary"><section class="service-summary" aria-labelledby="service-title"><div class="section-heading"><h2 id="service-title">Servicios contratados</h2>${status(customer.serviceStatus)}</div>${runtime.services.length > 1 ? `<button type="button" class="service-selector address" data-action="choose-service" aria-haspopup="dialog" aria-label="Elegir servicio">${e(addressLabel(customer.address))} ${icon('chevron-down')}</button>` : `<p class="address">${e(addressLabel(customer.address))}</p>`}${runtime.servicesUnavailable ? '<p class="field-hint">No pudimos verificar otros servicios asociados.</p>' : ''}<p class="muted">${e(planLabel(customer.plan))}</p>${contractedProducts()}${customer.products === null ? '<p class="field-hint">El detalle de tus adicionales todavía no está disponible.</p>' : ''}</section><section class="account-highlight" aria-labelledby="balance-title"><h2 id="balance-title">Estado de cuenta</h2><div class="balance-content"><div><p class="muted">${credit > 0 ? 'Saldo a favor' : 'Deuda actual'}</p><p class="amount">${money(credit > 0 ? credit : debt)}</p></div>${(runtime.mode !== 'phantom' || (Number.isFinite(debt) && debt > 0)) ? button('Pagar ahora', runtime.mode === 'phantom' ? 'payment-invoices' : 'pay', { attrs: runtime.mode === 'phantom' ? (runtime.paymentsEnabled ? '' : 'disabled') : 'data-id="2026-09"' }) : ''}</div></section></div><nav class="home-shortcuts" aria-label="Accesos rápidos"><a href="#/servicio">${icon('wifi')}<span><strong>Mi servicio</strong><small>Conexión, Wi-Fi y velocidad</small></span>${icon('chevron-right')}</a><a href="#/soporte">${icon('headphones')}<span><strong>Necesito ayuda</strong><small>Consultas y soporte</small></span>${icon('chevron-right')}</a></nav><section class="recent-invoices" aria-labelledby="recent-title"><h2 id="recent-title">Facturas recientes</h2>${invoices.length ? invoiceTable(invoices.slice(0, 2)) : '<p class="muted">No hay facturas para mostrar.</p>'}<a class="all-invoices" href="#/facturas">Ver facturas y pagos ${icon('arrow-right')}</a></section>`;
}
export function billing() {
  const movementsAvailable = runtime.paymentsEnabled || runtime.paymentHistoryEnabled;
  const movements = movementsAvailable && runtime.billingView === 'movements';
  const unpostedConfirmed = runtime.paymentItems.some(a => a.state === 'CONFIRMED' && !a.phantom_payment_posted);
  const tabs = movementsAvailable ? `<div class="billing-tabs" role="tablist" aria-label="Facturación"><button type="button" id="billing-tab-invoices" role="tab" aria-selected="${!movements}" aria-controls="billing-panel-invoices" data-action="billing-tab" data-view="invoices">Facturas</button><button type="button" id="billing-tab-movements" role="tab" aria-selected="${movements}" aria-controls="billing-panel-movements" data-action="billing-tab" data-view="movements">Movimientos</button></div>` : '';
  const invoiceContent = `<section id="billing-panel-invoices" role="tabpanel" aria-labelledby="billing-tab-invoices"><section class="debt-strip" aria-label="Resumen de deuda"><p>${credit > 0 ? 'Saldo a favor' : 'Deuda total'}</p><p class="amount">${money(credit > 0 ? credit : debt)}</p>${unpostedConfirmed ? '<p class="field-hint">Tu saldo puede tardar en reflejar pagos recientes.</p>' : ''}</section>${invoiceTable(invoices, true)}${runtime.nextOffset !== null ? button(runtime.invoicesLoading ? 'Cargando…' : 'Cargar más', 'more-invoices', { secondary: true, attrs: runtime.invoicesLoading ? 'disabled' : '' }) : ''}${runtime.mode === 'phantom' && runtime.endReached && invoices.length ? '<p class="field-hint">No hay más facturas para mostrar.</p>' : ''}${runtime.paymentsEnabled ? `<p class="billing-note">${icon('external-link')} Al presionar Pagar, serás redirigido al portal de SIRO, nuestro proveedor de pagos.</p>` : ''}</section>`;
  const movementContent = `<section id="billing-panel-movements" role="tabpanel" aria-labelledby="billing-tab-movements">${paymentPanel()}</section>`;
  return `<div class="billing-heading"><div><h1 tabindex="-1">Facturas</h1><p class="page-subtitle">${movements ? 'Pagos y movimientos recientes' : 'Estado de cuenta y comprobantes'}</p></div>${runtime.mode === 'phantom' ? `<button type="button" class="billing-refresh" data-action="billing-refresh" aria-label="Actualizar facturas y movimientos" title="Actualizar" ${runtime.billingRefreshing ? 'disabled aria-busy="true"' : ''}>${icon('refresh-cw')}</button>` : ''}</div>${tabs}${movements ? movementContent : invoiceContent}`;
}
export function service() { return servicePage(); }
export function support() {
  return `<h1 tabindex="-1">Soporte</h1>${runtime.mode === 'phantom' ? '<p class="field-hint">La consulta de tickets todavía no está disponible.</p>' : `<section class="ticket-summary" aria-labelledby="ticket-title"><div class="ticket-top"><span class="eyebrow">Ticket activo · ${ticket.id}</span>${status(ticket.status)}</div><h2 id="ticket-title">${ticket.title}</h2><p class="muted">Abierto el ${ticket.opened} · Última actualización ${ticket.updated}</p><button class="text-action" data-action="ticket">Ver seguimiento ${icon('arrow-right')}</button></section>`}<div class="two-columns support-columns"><section class="chat-highlight" aria-labelledby="chat-title"><h2 id="chat-title">Hablá con USITTEL</h2><p>Consultanos desde el chat.</p>${attentionButton()}</section><section class="second-column" aria-labelledby="help-title"><h2 id="help-title">Ayuda rápida</h2>${sectionLink('No tengo internet', 'help-internet')}${sectionLink('Tengo problemas con el Wi-Fi', 'help-wifi')}${sectionLink('Tengo una consulta sobre mi factura', 'help-invoice')}</section></div>`;
}
export function account() {
  return `<h1 tabindex="-1">Mi cuenta</h1><div class="two-columns"><section aria-labelledby="details-title"><h2 id="details-title">Datos personales</h2><dl class="profile-details"><div><dt>Nombre</dt><dd>${e(customer.name)}</dd></div><div><dt>Correo electrónico</dt><dd>${e(customer.email)}</dd></div><div><dt>Teléfono</dt><dd>${e(customer.phone || (runtime.mode === 'demo' ? 'Sin agregar' : null))}</dd></div></dl>${button('Editar datos de contacto', 'contact')}</section><section class="second-column security" aria-labelledby="security-title"><h2 id="security-title">Seguridad</h2>${sectionLink('Cambiar contraseña', 'password')}<button class="logout text-action" data-action="logout">${icon('log-out')} Cerrar sesión</button></section></div>`;
}

