import { servicePage, SPEEDTEST_URL } from './service-view.js';
import { homeAccount, homeConnection } from './home-presentation.js';
import { paymentPanel } from './payment-view.js';
import { customer, invoices, ticket, money, debt, credit, runtime, planLabel, addressLabel } from './data.js';
import { logo, status, button, input, invoiceTable, sectionLink, icon, escapeHTML as e } from './components.js';
function attentionButton() {
  return '<button type="button" class="button" data-action="chat">Hablar con nosotros</button>';
}

export function login() {
  return `<header class="login-header">${logo()}</header><main id="main" class="login-main"><h1 tabindex="-1">Mi USITTEL</h1><form id="login-form">${input('Usuario', 'username', { value: runtime.mode === 'demo' ? 'agustin.demo' : '', autocomplete: 'off' })}${input('Contraseña', 'password', { type: 'password', value: runtime.mode === 'demo' ? 'usittel-demo' : '', autocomplete: 'off' })}${button('Ingresar', '', { type: 'submit' })}${runtime.mode === 'demo' ? '<p class="login-note">Acceso de demostración. Usá los datos precargados.</p>' : '<p class="login-note">Ingresá con tus credenciales actuales de autogestión.</p>'}</form><section class="attention-login-help" aria-label="Ayuda para ingresar"><p>¿No podés ingresar?</p><div><button class="recovery-link" data-action="chat">Contactanos</button></div></section></main>`;
}
export function home() {
  const connection = homeConnection(customer, runtime.connectionDetails);
  const account = homeAccount(invoices, debt, runtime.warnings, runtime.endReached);
  const serviceId = runtime.selectedServiceId;
  return `<header class="home-intro"><h1 tabindex="-1">${customer.name ? 'Hola, ' + e(customer.name) : 'Inicio'}</h1><div class="home-contract">${runtime.services.length > 1 ? `<button type="button" class="service-selector" data-action="choose-service" aria-haspopup="dialog" aria-label="Elegir servicio">${icon('map-pin')}<span>${e(addressLabel(customer.address))}</span>${icon('chevron-down')}</button>` : `<p>${icon('map-pin')}${e(addressLabel(customer.address))}</p>`}${serviceId !== null && serviceId !== undefined && serviceId !== '' ? `<span>Contrato N.º ${e(serviceId)}</span>` : ''}</div>${runtime.servicesUnavailable ? '<p class="field-hint">No pudimos verificar otros servicios asociados.</p>' : ''}</header>
  <section class="home-hero home-hero-${connection.tone}" aria-labelledby="home-status-title"><div class="home-hero-main"><span class="home-hero-icon">${icon(connection.icon)}</span><div><p class="eyebrow">Estado del servicio</p><h2 id="home-status-title">${connection.title}</h2><p>${connection.description}</p>${customer.plan ? `<p class="home-plan">${e(planLabel(customer.plan))}</p>` : ''}</div></div><div class="home-hero-actions">${connection.suspended ? '<a class="button button-secondary" href="#/facturas">Ver facturas</a>' : '<a class="text-action" href="#/servicio">Ver mi servicio</a>'}${connection.tone !== 'success' ? button('Necesito ayuda','chat',{secondary:true}) : ''}</div></section>
  <section class="home-account" aria-labelledby="home-account-title"><div><p class="eyebrow">Tu cuenta</p><h2 id="home-account-title">Estado de cuenta</h2><p class="home-account-status home-account-${account.tone}">${icon(account.tone === 'success' ? 'check' : 'info')}${e(account.text)}</p></div><a class="text-action" href="#/facturas">Ver facturas ${icon('arrow-right')}</a></section>
  <nav class="home-actions" aria-label="Accesos rápidos"><h2>¿Qué necesitás hacer?</h2><div>${button('Configurar Wi-Fi','wifi-settings',{secondary:true,iconName:'wifi'})}<a class="button button-secondary" href="#/facturas">${icon('file-text')}Facturas</a><a class="button button-secondary" href="${SPEEDTEST_URL}" target="_blank" rel="noopener noreferrer">${icon('activity')}Test de velocidad</a>${button('Necesito ayuda','chat',{secondary:true,iconName:'headphones'})}</div></nav>`;
}
export function billing() {
  const movementsAvailable = runtime.paymentsEnabled || runtime.paymentHistoryEnabled;
  const movements = movementsAvailable && runtime.billingView === 'movements';
  const unpostedConfirmed = runtime.paymentItems.some(a => a.state === 'CONFIRMED' && !a.phantom_payment_posted);
  const tabs = movementsAvailable ? `<div class="billing-tabs" role="tablist" aria-label="Facturación"><button type="button" id="billing-tab-invoices" role="tab" aria-selected="${!movements}" aria-controls="billing-panel-invoices" data-action="billing-tab" data-view="invoices">Facturas</button><button type="button" id="billing-tab-movements" role="tab" aria-selected="${movements}" aria-controls="billing-panel-movements" data-action="billing-tab" data-view="movements">Movimientos</button></div>` : '';
  const invoiceContent = `<section id="billing-panel-invoices" role="tabpanel" aria-labelledby="billing-tab-invoices"><section class="debt-strip" aria-label="Resumen de deuda"><p>${credit > 0 ? 'Saldo a favor' : 'Deuda total'}</p><p class="amount">${money(credit > 0 ? credit : debt)}</p>${unpostedConfirmed ? '<p class="field-hint">Tu saldo puede tardar en reflejar pagos recientes.</p>' : ''}</section>${invoiceTable(invoices, true)}${runtime.nextOffset !== null ? button(runtime.invoicesLoading ? 'Cargando…' : 'Cargar más', 'more-invoices', { secondary: true, attrs: runtime.invoicesLoading ? 'disabled' : '' }) : ''}${runtime.mode === 'phantom' && runtime.endReached && invoices.length ? '<p class="field-hint">No hay más facturas para mostrar.</p>' : ''}${runtime.paymentsEnabled ? `<p class="billing-note">${icon('external-link')} Al presionar Pagar, serás redirigido al portal de SIRO, nuestro proveedor de pagos.</p>` : ''}</section>`;
  const movementContent = `<section id="billing-panel-movements" role="tabpanel" aria-labelledby="billing-tab-movements">${paymentPanel()}</section>`;
  return `<div class="billing-heading"><div><h1 tabindex="-1">Facturas</h1><p class="page-subtitle">${movements ? 'Pagos y movimientos recientes' : 'Estado de cuenta y comprobantes'}</p></div>${runtime.mode === 'phantom' ? `<button type="button" class="billing-refresh" data-action="billing-refresh" aria-label="Actualizar facturas y movimientos" title="Actualizar" ${runtime.billingRefreshing ? 'disabled aria-busy="true"' : ''}>${icon('refresh-cw')}</button>` : ''}</div>${tabs}${movements ? movementContent : invoiceContent}`;
}
export function service() { return servicePage(); }
export function support() {
  const faq = [
    ['internet','No tengo Internet, ¿qué puedo hacer?','Comprobá que el equipo esté encendido y revisá los cables visibles. Si ves una luz de alarma o seguís sin conexión, podemos ayudarte. No hagas un reset de fábrica.',button('Necesito ayuda','chat',{secondary:true})],
    ['wifi','El Wi-Fi anda lento o no llega bien','Internet y cobertura Wi-Fi no son lo mismo. Ubicá el router en un lugar despejado, lejos de obstáculos. La banda de 2,4 GHz suele llegar más lejos; la de 5 GHz puede rendir mejor cerca del equipo. Si necesitás más cobertura, consultanos por Mesh.',button('Necesito ayuda','chat',{secondary:true})],
    ['speed','¿Cómo hago un test de velocidad?','Pausá las descargas y, para medir con más precisión, usá cable o acercate al router.',`<a class="button button-secondary" href="${SPEEDTEST_URL}" target="_blank" rel="noopener noreferrer">${icon('external-link')}Abrir test de USITTEL</a>`],
    ['change-wifi','¿Cómo cambio el nombre o la contraseña de mi Wi-Fi?','Podés hacerlo desde Configurar Wi-Fi en Mi USITTEL. Al guardar, tus dispositivos se desconectarán y tendrás que volver a conectarlos.',button('Configurar Wi-Fi','wifi-settings',{secondary:true})],
    ['invoices','¿Dónde veo mis facturas?','En Facturas podés consultar los períodos disponibles y descargar cada documento cuando esté habilitado.','<a class="button button-secondary" href="#/facturas">Ver facturas</a>'],
    ['payment','¿Cómo pago una factura?','Abrí Facturas y elegí Pagar en una factura pendiente. Mi USITTEL te redirige al portal de pagos; la confirmación puede demorar en reflejarse.','<a class="button button-secondary" href="#/facturas">Ir a Facturas</a>'],
    ['symmetric','¿Qué significa Internet simétrico?','En los planes simétricos, la capacidad nominal de subida y bajada es la misma. El rendimiento medido puede variar según el dispositivo y la conexión Wi-Fi.',''],
    ['assistance','Necesito asistencia','Estamos para ayudarte con tu servicio o tu cuenta.',button('Abrir chat','chat',{secondary:true})],
  ];
  const demoTicket = runtime.mode === 'demo' && ticket ? `<section class="ticket-summary support-demo-ticket" aria-labelledby="ticket-title"><div class="ticket-top"><span class="eyebrow">Ticket activo · ${e(ticket.id)}</span>${status(ticket.status)}</div><h2 id="ticket-title">${e(ticket.title)}</h2><p class="muted">Abierto el ${e(ticket.opened)} · Última actualización ${e(ticket.updated)}</p><button class="text-action" data-action="ticket">Ver seguimiento ${icon('arrow-right')}</button></section>` : '';
  return `<h1 tabindex="-1">Soporte</h1><section class="support-intro" aria-labelledby="chat-title"><div><p class="eyebrow">Estamos para ayudarte</p><h2 id="chat-title">Hablá con USITTEL</h2><p>Consultanos por el chat de Mi USITTEL.</p></div>${attentionButton()}</section><section class="support-faq" aria-labelledby="help-title"><p class="eyebrow">Respuestas rápidas</p><h2 id="help-title">Preguntas frecuentes</h2><div class="faq-list">${faq.map(([id,title,answer,cta])=>`<details class="faq-item" name="support-faq" id="faq-${id}"><summary role="button" aria-expanded="false" aria-controls="faq-${id}-answer">${e(title)}${icon('chevron-down')}</summary><div class="faq-answer" id="faq-${id}-answer"><p>${e(answer)}</p>${cta}</div></details>`).join('')}</div></section>${demoTicket}`;
}
export function account() {
  return `<h1 tabindex="-1">Mi cuenta</h1><div class="two-columns"><section aria-labelledby="details-title"><h2 id="details-title">Datos personales</h2><dl class="profile-details"><div><dt>Nombre</dt><dd>${e(customer.name)}</dd></div><div><dt>Correo electrónico</dt><dd>${e(customer.email)}</dd></div><div><dt>Teléfono</dt><dd>${e(customer.phone || (runtime.mode === 'demo' ? 'Sin agregar' : null))}</dd></div></dl>${button('Editar datos de contacto', 'contact')}</section><section class="second-column security" aria-labelledby="security-title"><h2 id="security-title">Seguridad</h2>${sectionLink('Cambiar contraseña', 'password')}<button class="logout text-action" data-action="logout">${icon('log-out')} Cerrar sesión</button></section></div>`;
}

