import { paymentPanel } from './payment-view.js';
import { customer, invoices, ticket, money, debt, credit, nextDue, runtime, planLabel } from './data.js';
import { logo, status, button, input, invoiceTable, sectionLink, icon, escapeHTML as e } from './components.js';

export function login() {
  return `<header class="login-header">${logo()}</header><main id="main" class="login-main"><h1 tabindex="-1">Mi USITTEL</h1><form id="login-form">${input('Usuario', 'username', { value: runtime.mode === 'demo' ? 'agustin.demo' : '', autocomplete: 'off' })}${input('Contraseña', 'password', { type: 'password', value: runtime.mode === 'demo' ? 'usittel-demo' : '', autocomplete: 'off' })}${button('Ingresar', '', { type: 'submit' })}${runtime.mode === 'demo' ? '<p class="login-note">Acceso de demostración. Usá los datos precargados.</p>' : '<p class="login-note">Ingresá con tus credenciales actuales de autogestión.</p>'}</form><button class="recovery-link" data-action="recover">Olvidé mi contraseña</button></main>`;
}
export function home() {
  return `<h1 tabindex="-1">${customer.name ? 'Hola, ' + e(customer.name) : 'Inicio'}</h1><div class="dashboard-summary"><section class="service-summary" aria-labelledby="service-title"><div class="section-heading"><h2 id="service-title">${runtime.mode === 'phantom' ? 'Estado administrativo' : 'Tu servicio'}</h2>${status(customer.serviceStatus)}</div>${runtime.services.length > 1 ? `<button type="button" class="service-selector address" data-action="choose-service" aria-haspopup="dialog" aria-label="Elegir servicio">${e(customer.address)} ${icon('chevron-down')}</button>` : `<p class="address">${e(customer.address)}</p>`}${runtime.servicesUnavailable ? '<p class="field-hint">No pudimos verificar otros servicios asociados.</p>' : ''}<p class="muted">${e(planLabel(customer.plan))}</p></section><section class="account-highlight" aria-labelledby="balance-title"><h2 id="balance-title">Estado de cuenta</h2><div class="balance-content"><div><p class="muted">${credit > 0 ? 'Saldo a favor' : 'Deuda actual'}</p><p class="amount">${money(credit > 0 ? credit : debt)}</p></div><div class="due-summary"><p class="muted">Próximo vencimiento</p><p class="due-date">${e(nextDue)}</p></div>${button('Pagar ahora', runtime.mode === 'phantom' ? 'payment-invoices' : 'pay', { attrs: runtime.mode === 'phantom' ? (runtime.paymentsEnabled ? '' : 'disabled') : 'data-id="2026-09"' })}</div></section></div><section class="recent-invoices" aria-labelledby="recent-title"><h2 id="recent-title">Últimas facturas</h2>${invoiceTable(invoices.slice(0, 3))}<a class="all-invoices" href="#/facturas">Ver facturas ${icon('arrow-right')}</a></section>`;
}
export function billing() {
  return `<h1 tabindex="-1">Facturas</h1><p class="page-subtitle">Estado de cuenta y comprobantes</p><section class="debt-strip" aria-label="Resumen de deuda"><p>${credit > 0 ? 'Saldo a favor' : 'Deuda total'}</p><p class="amount">${money(credit > 0 ? credit : debt)}</p></section>${paymentPanel()}${invoiceTable(invoices, true)}${runtime.nextOffset !== null ? button(runtime.invoicesLoading ? 'Cargando…' : 'Cargar más', 'more-invoices', { secondary: true, attrs: runtime.invoicesLoading ? 'disabled' : '' }) : ''}${runtime.mode === 'phantom' && runtime.endReached && invoices.length ? '<p class="field-hint">No hay más facturas en la consulta actual.</p>' : ''}<p class="billing-note">${icon('external-link')} ${runtime.mode === 'phantom' ? 'Historial en validación de laboratorio. Se cargan hasta 10 facturas por vez. Los importes son totales de factura, no saldos pendientes.' : 'Al pagar, continuarás en el portal de SIRO.'}</p>`;
}
export function service() {
  return `<h1 tabindex="-1">Mi servicio</h1><div class="two-columns"><section aria-labelledby="plan-title"><div class="section-heading"><h2 id="plan-title" class="plan-title">${e(planLabel(customer.plan))}</h2>${status(customer.serviceStatus)}</div><dl class="service-details"><div><dt>Domicilio de instalación</dt><dd>${e(customer.address)}<br>${e(customer.city)}</dd></div><div><dt>Velocidad del plan</dt><dd>${e(customer.speed)}</dd></div></dl></section><section class="second-column" aria-labelledby="wifi-title"><h2 id="wifi-title">Wi-Fi</h2><dl class="service-details"><div><dt>Nombre de la red</dt><dd>${e(customer.network)}</dd></div></dl></section></div><section class="service-management" aria-labelledby="manage-title"><h2 id="manage-title">Gestionar mi servicio</h2><div class="plan-options">${sectionLink('Mejorar mi plan', 'upgrade-plan')}${sectionLink('Agregar servicios', 'addons')}${sectionLink('Hablar con un comercial', 'sales')}</div>${button('Cambiar nombre y contraseña', 'wifi')}<p class="field-hint">Configurá los datos de tu red Wi-Fi.</p></section><section class="speedtest-section" aria-labelledby="speed-title"><div><h2 id="speed-title">Speedtest</h2><p class="muted">${runtime.mode === 'phantom' ? 'Test de velocidad todavía no disponible.' : 'Probá cómo se verá el test de velocidad.'}</p><p class="demo-caption">${runtime.mode === 'phantom' ? 'Función no conectada' : 'Demostración · No mide tu conexión'}</p></div><div class="speed-metrics"><div><span>${icon('arrow-down')} Descarga</span><p><strong id="speed-down">—</strong> <small>Mbps</small></p></div><div><span>${icon('arrow-up')} Subida</span><p><strong id="speed-up">—</strong> <small>Mbps</small></p></div><div><span>${icon('activity')} Latencia</span><p><strong id="speed-ping">—</strong> <small>ms</small></p></div></div><progress id="speed-progress" value="0" max="100" hidden aria-label="Progreso de la demostración"></progress><div class="speed-footer">${button(runtime.mode === 'phantom' ? 'Iniciar test' : 'Probar demostración', 'speedtest', { secondary: true, iconName: 'play' })}<span id="speed-status" class="muted" role="status"></span></div></section><div class="support-link"><p>¿Necesitás ayuda con tu servicio?</p><a href="#/soporte">Ir a soporte</a></div>`;
}
export function support() {
  return `<h1 tabindex="-1">Soporte</h1>${runtime.mode === 'phantom' ? '<p class="field-hint">La consulta de tickets todavía no está disponible.</p>' : `<section class="ticket-summary" aria-labelledby="ticket-title"><div class="ticket-top"><span class="eyebrow">Ticket activo · ${ticket.id}</span>${status(ticket.status)}</div><h2 id="ticket-title">${ticket.title}</h2><p class="muted">Abierto el ${ticket.opened} · Última actualización ${ticket.updated}</p><button class="text-action" data-action="ticket">Ver seguimiento ${icon('arrow-right')}</button></section>`}<div class="two-columns support-columns"><section class="chat-highlight" aria-labelledby="chat-title"><h2 id="chat-title">Hablá con USITTEL</h2><p>Consultanos desde el chat.</p>${button('Abrir chat', 'chat', { iconName: 'message-circle' })}</section><section class="second-column" aria-labelledby="help-title"><h2 id="help-title">Ayuda rápida</h2>${sectionLink('No tengo internet', 'help-internet')}${sectionLink('Tengo problemas con el Wi-Fi', 'help-wifi')}${sectionLink('Tengo una consulta sobre mi factura', 'help-invoice')}</section></div>`;
}
export function account() {
  return `<h1 tabindex="-1">Mi cuenta</h1><div class="two-columns"><section aria-labelledby="details-title"><h2 id="details-title">Datos personales</h2><dl class="profile-details"><div><dt>Nombre</dt><dd>${e(customer.name)}</dd></div><div><dt>Correo electrónico</dt><dd>${e(customer.email)}</dd></div><div><dt>Teléfono</dt><dd>${e(customer.phone || (runtime.mode === 'demo' ? 'Sin agregar' : null))}</dd></div></dl>${button('Editar datos de contacto', 'contact')}</section><section class="second-column security" aria-labelledby="security-title"><h2 id="security-title">Seguridad</h2>${sectionLink('Cambiar contraseña', 'password')}<button class="logout text-action" data-action="logout">${icon('log-out')} Cerrar sesión</button></section></div>`;
}

