const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  let checks = 0;
  const check = (name, fn) => { fn(); checks++; };
  const data = await import('../js/data.js');
  const { homeConnection, homeAccount } = await import('../js/home-presentation.js');
  const { operationAlert } = await import('../js/components.js');
  const { home, support, account } = await import('../js/views.js');
  const { servicePage } = await import('../js/service-view.js');
  const customer = { name:'Cliente', address:'Calle 123', plan:'Internet 300 Mbps', serviceStatus:'Activo', connectionState:'online' };
  check('online', () => assert.match(homeConnection(customer,null).title,/en línea/));
  check('offline', () => assert.equal(homeConnection({...customer,connectionState:'offline'},null).tone,'error'));
  check('desconocido', () => assert.equal(homeConnection({...customer,connectionState:null},null).tone,'warning'));
  check('suspendido explícito', () => assert.equal(homeConnection({...customer,serviceStatus:'SUSPENDIDO'},null).title,'Servicio suspendido'));
  check('sin inferir suspensión por deuda', () => assert.notEqual(homeConnection(customer,null).title,'Servicio suspendido'));
  check('detalle de conexión seleccionado', () => assert.equal(homeConnection(customer,{connectionState:'offline'}).tone,'error'));
  const invoice = status => ({ status });
  check('cuenta al día', () => assert.equal(homeAccount([invoice('Pagada')],0,[],true).text,'Estás al día.'));
  check('una factura', () => assert.equal(homeAccount([invoice('Pendiente')],100,[],true).text,'1 factura pendiente.'));
  check('varias facturas', () => assert.equal(homeAccount([invoice('Pendiente'),invoice('Pendiente')],100,[],true).text,'2 facturas pendientes.'));
  check('historial paginado no afirma total', () => assert.match(homeAccount([invoice('Pendiente')],100,[],false).text,/Al menos 1/));
  check('deuda sin factura identificada', () => assert.match(homeAccount([],100,[],true).text,/saldo pendiente/));
  check('sin balance no afirma al día', () => assert.notEqual(homeAccount([],null,[],true).text,'Estás al día.'));
  check('facturas no disponibles', () => assert.match(homeAccount([],0,['INVOICES_UNAVAILABLE'],true).text,/No pudimos confirmar/));
  check('conciliación ambigua', () => assert.match(homeAccount([],0,['ACCOUNT_RECONCILIATION'],true).text,/No pudimos confirmar/));
  for (const tone of ['success','warning','error','info']) {
    check(`alert ${tone}`, () => { const html=operationAlert(tone,'Título','Detalle');assert.match(html,new RegExp(`operation-alert-${tone}`));assert.match(html,/Título/);assert.match(html,/Detalle/); });
  }
  check('alert escapa texto', () => assert.doesNotMatch(operationAlert('error','<script>'),/<script>/));
  const overview = (products, invoiceItems = []) => data.applyOverview({customer, invoices:{items:invoiceItems,nextOffset:null,endReached:true},account:{debt:0,credit:0},warnings:[], servicePresentation:products, commercialOffers:[]});
  data.runtime.selectedServiceId='5726';
  data.runtime.services=[{id:'5726',address:'Calle 123'},{id:'6000',address:'Otra 456'}];
  overview({known:true,items:[]});
  check('Internet solo oculta Tus servicios', () => assert.doesNotMatch(servicePage(),/Tus servicios/));
  check('products vacíos conservan plan', () => assert.match(servicePage(),/Internet 300 Mbps/));
  check('home contrato y selector', () => {const html=home();assert.match(html,/Contrato N.º 5726/);assert.match(html,/data-action="choose-service"/);});
  check('home sin montos ni facturas detalladas', () => {const html=home();assert.doesNotMatch(html,/\$|invoice-table|Facturas recientes/);});
  check('home acceso Central y Wi-Fi', () => {const html=home();assert.match(html,/data-action="chat"/);assert.match(html,/data-action="wifi-settings"/);});
  const homeFixture=(changes,items=[],amount=0) => {
    data.applyOverview({customer:{...customer,...changes},invoices:{items,nextOffset:null,endReached:true},account:{debt:amount,credit:0},warnings:[],servicePresentation:{known:true,items:[]},commercialOffers:[]});
    return home();
  };
  check('home online', () => assert.match(homeFixture({connectionState:'online'}),/Tu conexión está en línea/));
  check('home offline', () => assert.match(homeFixture({connectionState:'offline'}),/Tu servicio está sin conexión[\s\S]*Necesito ayuda/));
  check('home estado desconocido', () => assert.match(homeFixture({connectionState:null}),/No pudimos consultar el estado de tu conexión/));
  check('home suspendido sin inventar causa', () => {const html=homeFixture({serviceStatus:'Suspendido'});assert.match(html,/Servicio suspendido/);assert.doesNotMatch(html,/por falta de pago/);});
  check('suspendido y cuenta al día independientes', () => {const html=homeFixture({serviceStatus:'Suspendido'},[invoice('Pagada')],0);assert.match(html,/Servicio suspendido/);assert.match(html,/Estás al día/);assert.match(html,/Ver facturas/);assert.match(html,/Necesito ayuda/);});
  check('suspendido y factura pendiente independientes', () => {const html=homeFixture({serviceStatus:'Suspendido'},[invoice('Pendiente')],100);assert.match(html,/Servicio suspendido/);assert.match(html,/1 factura pendiente/);assert.doesNotMatch(html,/suspendido por deuda/i);});
  check('home una pendiente', () => assert.match(homeFixture({},[invoice('Pendiente')],100),/1 factura pendiente/));
  check('home varias pendientes', () => assert.match(homeFixture({},[invoice('Pendiente'),invoice('Pendiente')],200),/2 facturas pendientes/));
  check('home al día', () => assert.match(homeFixture({},[invoice('Pagada')],0),/Estás al día/));
  overview({known:true,items:[{label:'Sensa',quantity:null}]});
  check('Sensa aparece', () => assert.match(servicePage(),/Tus servicios[\s\S]*Sensa/));
  overview({known:true,items:[{label:'Sensa',quantity:null},{label:'Set Top Box',quantity:2},{label:'Producto informado',quantity:null}]});
  check('varios y desconocido saneado', () => {const html=servicePage();assert.match(html,/Set Top Box[\s\S]*× 2/);assert.match(html,/Producto informado/);});
  overview(null);
  check('products null informa sin afirmar ausencia', () => {const html=servicePage();assert.match(html,/no está disponible/);assert.doesNotMatch(html,/No tenés servicios/);});
  check('sin test duplicado bajo Wi-Fi', () => {const html=servicePage();const wifi=html.match(/<section class="service-wifi"[\s\S]*?<\/section>/)?.[0];assert.ok(wifi);assert.doesNotMatch(wifi,/Test de velocidad|show-speedtest/);});
  data.runtime.commercialOffers=[{id:'internet_500',type:'speed',public_name:'Internet 500 Mbps',description:'Más velocidad.',price_monthly:43999,currency:'ARS'}];
  check('mejora de velocidad deriva al chat sin acción de escritura', () => {const html=servicePage();assert.match(html,/Solicitar mejora de plan/);assert.match(html,/data-action="chat" data-chat-topic="upgrade-speed"/);assert.doesNotMatch(html,/data-action="upgrade|upgrade-change|soap-write/);});
  data.runtime.commercialOffers=[];
  const faq=support();
  check('9 preguntas inline', () => assert.equal((faq.match(/class="faq-item"/g)||[]).length,9));
  check('FAQ accesible', () => {assert.match(faq,/role="button" aria-expanded="false" aria-controls="faq-internet-answer"/);assert.match(faq,/name="support-faq"/);});
  check('FAQ sin modales', () => assert.doesNotMatch(faq,/help-internet|openDialog|data-action="help-/));
  check('FAQ CTAs internas y Central', () => {assert.match(faq,/href="#\/servicio"/);assert.match(faq,/href="#\/facturas"/);assert.match(faq,/data-action="chat"/);});
  check('FAQ ayuda técnica y mejora de servicio', () => {assert.match(faq,/No hagas un reset de fábrica/);assert.match(faq,/Quiero cambiar o mejorar mi servicio/);assert.match(faq,/Necesito asistencia técnica/);});
  check('FAQ test existente', () => assert.match(faq,/velocidad\.usittel\.com\.ar\/speedtest/));
  const app=fs.readFileSync(path.join(__dirname,'..','js','app.js'),'utf8');
  check('toggle cierra otro FAQ', () => assert.match(app,/\.faq-item\[open\][\s\S]*other\.open = false/));
  check('FAQ actualiza aria-expanded', () => assert.match(app,/setAttribute\('aria-expanded', String\(item\.open\)\)/));
  check('Wi-Fi APPLIED y UNKNOWN diferenciados', () => {assert.match(app,/response\.state==='APPLIED'[\s\S]*operationAlert\('success'[\s\S]*operationAlert\('warning'/);assert.match(app,/error\.code==='WIFI_INPUT'[\s\S]*operationAlert\('error'/);assert.match(app,/rejectedBeforeWrite[\s\S]*operationAlert\('warning'/);});
  check('Central no recibe identidad', () => {assert.doesNotMatch(app,/openCentralChat\([^)]*(?:ida|customer)/);assert.doesNotMatch(faq,/WhatsApp|wa\.me/);});
  check('Mi USITTEL no ofrece WhatsApp como fallback', () => {const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.doesNotMatch(html,/wa\.me|data-central-fallback|WhatsApp/);assert.doesNotMatch(app,/data-central-fallback|wa\.me/);assert.match(app,/chat no está disponible en este momento/);});
  overview({known:true,items:[]});
  check('Mi cuenta muestra datos y contrato seleccionado', () => {const html=account();assert.match(html,/Tus datos/);assert.match(html,/Calle 123/);assert.match(html,/Contrato seleccionado[\s\S]*5726/);assert.match(html,/data-action="logout"/);});
  check('Mi cuenta sigue selected_ida al cambiar de contrato', () => {data.runtime.selectedServiceId='6000';data.applyOverview({customer:{...customer,address:'Otra 456'},invoices:{items:[],nextOffset:null,endReached:true},account:{debt:0,credit:0},warnings:[],servicePresentation:{known:true,items:[]},commercialOffers:[]});const html=account();assert.match(html,/Contrato seleccionado[\s\S]*6000/);assert.match(html,/Otra 456/);assert.doesNotMatch(html,/5726|Calle 123/);data.runtime.selectedServiceId='5726';});
  check('Mi cuenta deriva cambios y acceso a Central', () => {const html=account();assert.match(html,/Actualizar mis datos[\s\S]*data-chat-topic="access-help"/);assert.equal((html.match(/data-action="chat"/g)||[]).length,2);assert.doesNotMatch(html,/data-action="contact"|data-action="password"|WhatsApp/);});
  check('Mi cuenta omite datos vacíos y escapa valores', () => {data.applyOverview({customer:{...customer,name:'<script>',email:'',phone:null,address:''},invoices:{items:[],nextOffset:null,endReached:true},account:{debt:0,credit:0},warnings:[],servicePresentation:{known:true,items:[]},commercialOffers:[]});const html=account();assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>|Correo electrónico|Teléfono|Domicilio del servicio/);});
  check('logout limpia estado local y reinicia sesión', () => {assert.match(app,/action === 'logout'[\s\S]*request\('logout'/);assert.match(app,/action === 'logout'[\s\S]*clearData\(\)[\s\S]*await boot\(\)/);});
  check('Wi-Fi no muestra WhatsApp de backend', () => assert.match(app,/error\.code==='WIFI_UNAVAILABLE'[\s\S]*Contactanos para recibir ayuda/));
  await data.initialize('demo');
  check('seguimiento de ticket demo permanece', () => assert.match(support(),/data-action="ticket"[\s\S]*Ver seguimiento/));
  console.log(`presentation: ${checks} assertions`);
})().catch(error => { console.error(error); process.exitCode = 1; });
